targets:
  prod:
    variables:
      catalog: cfdb_free_prod
      warehouse_id: "8804e40a7a070e15"  # Use production warehouse ID
    workspace:
      host: https://dbc-08c10e87-023f.cloud.databricks.com
    
    # Production-specific configurations
    resources:
      pipelines:
        cfdb_dlt_pipeline:
          development: false
          continuous: false
          photon: true  # Enable Photon for production performance
          
      jobs:
        cfdb_data_refresh:
          # Standard daily schedule for production
          trigger:
            cron:
              quartz_cron_expression: "0 6 * * *"  # Daily at 6 AM
              timezone_id: "America/Chicago"
              
        cfdb_test_suite:
          # Disable test suite in production
          pause_status: PAUSED
          
      quality_monitors:
        # Standard production monitoring schedule
        cfdb_bronze_data_quality:
          schedule:
            quartz_cron_expression: "0 8 * * *"  # Daily at 8 AM
        cfdb_silver_games_quality:
          schedule:
            quartz_cron_expression: "0 9 * * *"  # Daily at 9 AM
        cfdb_gold_predictions_quality:
          schedule:
            quartz_cron_expression: "0 10 * * *"  # Daily at 10 AM
        cfdb_advanced_stats_quality:
          schedule:
            quartz_cron_expression: "0 11 * * *"  # Daily at 11 AM
            
      model_serving_endpoints:
        cfdb_game_predictions:
          config:
            served_entities:
              - workload_size: Medium  # Larger workload for production
                scale_to_zero_enabled: false  # Keep always available